### ISSUE TITLE
(3) [install] atomic-openshift-install should only output relevant information

### ISSUE THREAD

**Issue by tbielawa** [openshift/openshift-ansible#2445]
* https://trello.com/c/DSwwizwP/74-3-install-atomic-openshift-install-should-only-output-relevant-information

# Original Description

> tl;dr We want a progress bar in oo-install instead of dumping raw ansible output to the screen.  In addition we want to display human reading output to the screen if it's relevant.

> **Background**: 

> Today oo-install is very OpenShift branded.  This is most obvious when ansible is run and the output is presented to the user.  This is primarily for historical reasons.  However, even if the openshift-ansible playbooks are made more generic or branded as Origin we still have the same problem.  What we want is to shield the admin from this in the UI.

> One way to do this is to create a callback_filter. 

> We actually already use a callback filter to write out the json returned from the task that collects facts about the hosts.  We don't use that filter when we trigger the actual install though.

> We likely want a new filter that establishes some sort of pipe between the installer (instead of just writing a yaml file).  The installer would listen of events that ansible sends to tell it about progress.  We would likely maintain a whitelist of events that we want to actually display to the user.  For example, "creating a tmp directory" is not something we'd want to display to the admin.  "Installing the Master container" is however.

> Ideally we'd use the `click` library's support for progress bars to provide feedback to the end user.

----

## Tasks
- [ ] Switch to calling ansible as a library (utilize the Ansible API to execute the runner)
- [ ] Utilize callback to collate errors (save displaying the errors until the end of the run, and make sure they're saved somewhere. preferrably unique and intelligently named)
- [ ] Utilize callback to do full output to a log (Even though some output was masked from `stdout` **all** output must be collected into a log file)
- [ ] Utilize callback to display current playbook and role (Process events emitted by the ansible API to identify meaningful status/state changes so that we can provide status updates to the user running the install) 

----

**Comment by tbielawa** [comment]
Standard test procedure for the first experiments will be in running the `playbooks/byo/openshift_facts.yml` playbook.

In this gist I have the inventory file as well as the result from running that playbook

* https://gist.github.com/tbielawa/c3de42160addbb90da4db1b54bbc89f6

My first learning objective here is to get the skipped tasks to not appear in the standard output.

**Comment by tbielawa** [comment]
Some general information I've discovered so far

Filtering out `skipped`s is easy. But only for the result. The part where ansible says what task is about to run/is running you can't just blanket skip. Because the `skipped` result hasn't arrived yet. That is to say, we can skip printing results, but skipping the result header isn't a given. Take this for example:

> TASK [fail] ********************************************************************
> skipping: [localhost]

We can set `CallbackModule.v2_runner_on_skipped` to just `pass` (not dump any output) but that leaves us with output like this:

> TASK [fail] ********************************************************************

Little strange, isn't it?

**Comment by tbielawa** [comment]
This may be more involved than we originally estimated. I think it's easier to imagine the "expected" trimmed output if we change the context to a more modern space, the web browser.

Imagine if you will a web UI that runs your install playbooks through ansible. Maybe there's a web socket connecting the web UI to something integrated with the ansible playbook runner.

Now, if we want to update the user with little [toast notifications](http://ux.stackexchange.com/questions/11998/what-is-a-toast-notification) we wouldn't want to spam the screen with every single finished task. I think we'd want to at least start with printing out when a new play begins. For example, referencing the GIST in the previous comment, we would we popping up just these toasts:

> PLAY [localhost] ***************************************************************
> PLAY [localhost] ***************************************************************
> PLAY [l_oo_all_hosts] **********************************************************
> PLAY [Populate config host groups] *********************************************
> PLAY [Gather Cluster facts] ****************************************************

We've got some issues to address here already.

When a play does not include a `name` parameter the output falls back to printing out the value of the `hosts` key in some way.

* `playbooks/byo/openshift_facts.yml` begins with including `verify_ansible_version.yml`
* this play also does not have a `name`, so we see `localhost` printed first
* Then we get to the first play in `openshift_facts`, again, no name on this play so we see `localhost`
* Next we have a play with one task that just `include_vars` another file, so we see `l_oo_all_hosts` as the PLAY output
* Then we move on to an include statement for `evaluate_groups.yml`, this has a `name` set, so we see `Populate config host groups`
* Finally we have the main play we've been waiting for (which also has a `name`): `Gather Cluster facts`

**Comment by tbielawa** [comment]
Back to the issue at hand, trimming down our output in the quick installer, I think we're going to want to begin implementing a play naming scheme. For example, those setup plays in the previous comment that only printed out "localhost" we might want to give an actual name and apply a string tag to it so we can skip printing/toasting it in the abbreviated output.

For example, in `openshift_facts.yml` we have this presently (snippet):

```yaml
- hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
  - include_vars: openshift-cluster/cluster_hosts.yml
  - add_host:
      name: "{{ item }}"
      groups: l_oo_all_hosts
    with_items: "{{ g_all_hosts }}"
```

Let's say we don't want to print this in our abbreviated output, we might apply a tag like "noprint" (or whatever color you want to [paint the bike shed](http://bikeshed.com)) in this way:

```yaml
- name: noprint build host groups
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
  - include_vars: openshift-cluster/cluster_hosts.yml
  - add_host:
      name: "{{ item }}"
      groups: l_oo_all_hosts
    with_items: "{{ g_all_hosts }}"
```

**Comment by tbielawa** [comment]
Here's an example of all of the `PLAY` log output from an older install log where I set up a multi-master cluster back in July

```
PLAY [localhost] ***************************************************************
PLAY [l_oo_all_hosts] **********************************************************
PLAY [Populate config host groups] *********************************************
PLAY [Initialize host facts] ***************************************************
PLAY [Gather and set facts for node hosts] *************************************
PLAY [Set oo_options] **********************************************************
PLAY [Set etcd facts needed for generating certs] ******************************
PLAY [Create temp directory for syncing certs] *********************************
PLAY [Configure etcd certificates] *********************************************
PLAY [Configure first etcd host] ***********************************************
PLAY [Configure remaining etcd hosts] ******************************************
PLAY [Delete temporary directory on localhost] *********************************
PLAY [Configure nfs hosts] *****************************************************
PLAY [Configure load balancers] ************************************************
PLAY [Set master facts and determine if external etcd certs need to be generated] ***
PLAY [Create temp directory for syncing certs] *********************************
PLAY [Configure etcd certificates] *********************************************
PLAY [Copy the external etcd certs to the masters] *****************************
PLAY [Determine if master certificates need to be generated] *******************
PLAY [Configure master certificates] *******************************************
PLAY [Check for cached session secrets] ****************************************
PLAY [Generate master session secrets] *****************************************
PLAY [Parse named certificates] ************************************************
PLAY [Deploy named certificates] ***********************************************
PLAY [Configure master instances] **********************************************
PLAY [Configure master instances] **********************************************
PLAY [Configure master instances] **********************************************
PLAY [Delete temporary directory on localhost] *********************************
PLAY [Configure flannel] *******************************************************
PLAY [Additional master configuration] *****************************************
PLAY [Gather and set facts for node hosts] *************************************
PLAY [Create temp directory for syncing certs] *********************************
PLAY [Create node certificates] ************************************************
PLAY [Deploy node certificates] ************************************************
PLAY [Evaluate node groups] ****************************************************
PLAY [Configure node instances] ************************************************
PLAY [Gather and set facts for flannel certificatess] **************************
PLAY [Configure flannel etcd certificates] *************************************
PLAY [Copy the external etcd flannel certs to the nodes] ***********************
PLAY [Additional node config] **************************************************
PLAY [Delete temporary directory on localhost] *********************************
PLAY [Set schedulability] ******************************************************
PLAY [Create persistent volumes] ***********************************************
PLAY [Create Hosted Resources] *************************************************
```

Some of those actually look pretty good, as far as trimming down our output for the quick installer goes.

**Comment by tbielawa** [comment]
For reference, that's 45 different plays and that playbook took 34 minutes to run.

**Comment by tbielawa** [comment]
I'm going to guess that without already knowing what's going on a new user probably wouldn't have any concept of "progress" from the play output though. For example, "Create persistent volumes" and "Create Hosted Resources" don't give you any sense of how close to the end you are.

Still not sure how we can convey that to users (even if we weren't trying to trim down the output).

**Comment by sdodson** [comment]
If ansible knows the total number of plays, I think it should, but maybe
not exposed. I think "Play X/Y - Name" is good enough.

**Comment by tbielawa** [comment]
@sdodson I'll be quite happy when I find the API endpoint that exposes that kind of information

**Comment by tbielawa** [comment]
Shouldn't be too difficult to find given the `--list-tasks` option flag. Running 

> ansible-playbook --list-tasks -i inventory/byo/hosts.tbielawa.multi ./playbooks/byo/config.yml >/tmp/multi-master--list-tasks

Produces a copious amount of output

* https://gist.github.com/tbielawa/d6644c929fe7fab865f3d21b98f5b697 (~3000 lines of output)

**Comment by tbielawa** [comment]
@sdodson that would up being easier than I expected

https://gist.github.com/tbielawa/c00f38e43375214c3aff9fa24cb179ec

```

----------------------------------
Beginning play 1 of 5

TASK [Verify Ansible version is greater than or equal to 2.1.0.0] **************

----------------------------------
Beginning play 2 of 5

TASK [include_vars] ************************************************************
ok: [localhost]

TASK [add_host] ****************************************************************
changed: [localhost] => (item=192.168.0.14)

----------------------------------
Beginning play 3 of 5

TASK [include_vars] ************************************************************
ok: [192.168.0.14]

....
```

**Comment by tbielawa** [comment]
Code pushed to branch.

**Comment by tbielawa** [comment]
Creating a PR now to get CI involved in this junk

**Comment by tbielawa** [comment]
Alrighty. The challenge now is getting the quick installer to utilize the new callback changes. Figured out that the quick installer is using some of the ansible ENV vars to point to the configs and plugin dirs.

Going to end up having to create a new sub-package in the [openshift-ansible.spec](https://github.com/openshift/openshift-ansible/blob/master/openshift-ansible.spec) file to install the callback plugins.

Probs gotta update the [ansible.cfg](https://github.com/openshift/openshift-ansible/blob/master/utils/etc/ansible.cfg) file too to point to the new `stdout` plugin.

**Comment by tbielawa** [comment]
Latest commits bring back the ansible log file functionality. I'm not happy with it though as I had to effectively copy and paste every method that got overridden in the callback plugin, but it works.

**Comment by tbielawa** [comment]
PR has been merged. Closing this issue now.
